language: php
sudo: required

matrix:
  include:
    - php: 5.5
      env: DB=none
    - php: 5.4
      env: DB=mysqli
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
    - php: 7.0
      env: DB=mysqli
    - php: 7.1
      env: DB=mysqli
    - php: 7.2
      env: DB=mysqli
  fast_finish: true

env:
  global:
    - EXTNAME="lordbeaver/chevereto"
    - SNIFF="1"
    - IMAGE_ICC="1"
    - EPV="1"
    - PHPBB_BRANCH="3.1.x"

branches:
  only:
    - master
    - develop
    - /^develop-.*$/
    - /^\d+(\.\d+)?\.x$/

before_install:
  - sudo mkdir travis
  - git clone "https://github.com/phpbb/phpbb-ext-acme-demo.git"
  - sudo cp phpbb-ext-acme-demo/phpunit.xml.dist ./
  - sudo cp phpbb-ext-acme-demo/travis/prepare-phpbb.sh travis
  - sudo rm -rf phpbb-ext-acme-demo

install:
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION
  - sh -c "if [ '$EPV' != '0' -a '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'none' ]; then cd phpBB; composer remove sami/sami --dev --no-interaction; composer require phpbb/epv:dev-master --dev --no-interaction --ignore-platform-reqs; cd ../; fi"

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php
  - sh -c "if [ '$EPV' != '0' -a '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'none' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
